services:
  app:
    build:
      context: ./hotel-booking-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=student
      - DB_NAME=hotel
      - DB_PORT=5432

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: student
      POSTGRES_DB: hotel
    ports:
      - "5432:5432"